### ISSUE TITLE
请问方便和您沟通一下么

### ISSUE THREAD

**Issue by foreverMaziqi** [poofee/FEEM#1]
您好，我们公司是做电力行业商业有限元分析软件的，目前需要有限元方面的技术支持，请问方便和您沟通一下么，我的QQ:458612149

**Comment by Poofee** [comment]
好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: foreverMaziqi <notifications@github.com&gt;
发送时间: 2019年9月7日 15:11
收件人: Poofee/FEEM <FEEM@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Poofee/FEEM] 请问方便和您沟通一下么 (#1)
